#!/usr/bin/env bash
# Idempotent deployer for the SP runner farm.
#
#   ./deploy.sh init                 generate secrets/ (tokens, keys, configs)
#   ./deploy.sh push <host-id>       install/upgrade one host from hosts.toml
#   ./deploy.sh push all             every host in hosts.toml
#   ./deploy.sh fingerprint <id>     re-print a remote agent's TLS fingerprint
#
# Workstation needs: bash, ssh, rsync, python3, openssl.
# Each host's ssh user needs sudo (a password prompt is fine — deploy uses
# `ssh -t sudo`). Use SSH keys, never a password on the command line.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"
SECRETS="$HERE/secrets"
HOSTS_TOML="$HERE/hosts.toml"
REMOTE_STAGE="/tmp/sp-runner-deploy"
RUNNER_USER="ghrunner"

die() { echo "deploy: $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null || die "missing tool: $1"; }
have ssh; have rsync; have python3; have openssl
[[ -f "$HOSTS_TOML" ]] || die "no hosts.toml — cp hosts.toml.example hosts.toml and edit"

# --- hosts.toml: parsed once by a tiny dependency-free reader -----------------
# Emits one line per host:  <id>\t<ssh>\t<role>\t<lan_cidr>\t<allow_from>
_hosts() {
    python3 - "$HOSTS_TOML" <<'PY'
import re, sys
text = open(sys.argv[1]).read()
hosts, cur = [], None
for raw in text.splitlines():
    line = raw.split("#", 1)[0].strip()
    if not line:
        continue
    if line == "[[host]]":
        cur = {}; hosts.append(cur); continue
    m = re.match(r'([A-Za-z_]+)\s*=\s*"([^"]*)"', line)
    if m and cur is not None:
        cur[m.group(1)] = m.group(2)
for h in hosts:
    print("\t".join([h.get("id",""), h.get("ssh",""), h.get("role","agent"),
                     h.get("lan_cidr",""), h.get("allow_from","")]))
PY
}
host_row() { _hosts | awk -F'\t' -v id="$1" '$1==id{print; found=1} END{exit !found}'; }
host_field() { host_row "$1" | cut -f"$2"; }
all_host_ids() { _hosts | cut -f1; }
manager_id() { _hosts | awk -F'\t' '$3=="manager"{print $1; exit}'; }
manager_addr() { _hosts | awk -F'\t' '$3=="manager"{split($2,a,"@"); print a[2]; exit}'; }

rand48() { openssl rand -base64 48 | tr -d '\n'; }

# ============================================================ init
cmd_init() {
    mkdir -p "$SECRETS"; chmod 700 "$SECRETS"
    local mgr_toml="$SECRETS/manager.toml"
    local mgr_addr; mgr_addr="$(manager_addr)"
    [[ -n "$mgr_addr" ]] || die "hosts.toml needs exactly one host with role = \"manager\""

    if [[ -f "$mgr_toml" ]]; then
        echo "[init] $mgr_toml exists — keeping it (delete to regenerate from scratch)"
    else
        FARM_SECRET_KEY="$(rand48)" MGR_ADDR="$mgr_addr" python3 - "$HOSTS_TOML" "$mgr_toml" <<'PY'
import base64, os, re, secrets, sys
hosts_toml, out = sys.argv[1], sys.argv[2]

# reuse the same tiny reader
text = open(hosts_toml).read()
hosts, cur = [], None
for raw in text.splitlines():
    line = raw.split("#", 1)[0].strip()
    if not line: continue
    if line == "[[host]]":
        cur = {}; hosts.append(cur); continue
    m = re.match(r'([A-Za-z_]+)\s*=\s*"([^"]*)"', line)
    if m and cur is not None:
        cur[m.group(1)] = m.group(2)

def tok(): return base64.b64encode(secrets.token_bytes(36)).decode()
mgr_addr = os.environ["MGR_ADDR"]

body = f'''# Generated by deploy.sh init. Fill in [github] and drop the App key at
# secrets/github-app.pem, then: ./deploy.sh push <host-id>

[server]
secret_key = "{os.environ['FARM_SECRET_KEY']}"
session_hours = 12
secure_cookies = false

[github]
org = "your-org"
app_id = 0
installation_id = 0
private_key_file = "/home/ghrunner/.config/sp-runner/github-app.pem"

[watermarks]
warn = 75
prune = 85
freeze = 92

[fleet]
reap_grace_minutes = 15
reconcile_seconds = 30
disk_sample_seconds = 60
disk_history_days = 30

[api]
# X-API-Key values for /api/v1/* and /metrics. One is generated here.
keys = ["{tok()}"]
metrics_public = false

[events]
track_jobs = false          # emit job.started / job.finished (chatty)

[plugins]
enabled = []                # e.g. ["webhook", "prometheus"] — see docs/PLUGINS.md

# [plugins.prometheus]      # exposes /metrics for Grafana
#
# [plugins.webhook]         # POST events to a phone notifier
# [[plugins.webhook.targets]]
# url    = "https://ntfy.sh/YOUR-TOPIC"
# events = ["host.degraded", "host.recovered", "disk.freeze", "slot.crashloop"]
# format = "ntfy"
'''

for h in hosts:
    hid = h["id"]
    is_mgr = h.get("role") == "manager"
    addr = "127.0.0.1" if is_mgr else h["ssh"].split("@")[-1]
    body += f'''
[[hosts]]
id = "{hid}"
address = "{addr}"
agent_url = "https://{addr}:8181"
agent_token = "{tok()}"
manager_token = "{tok()}"
agent_tls_fingerprint = "SET_BY_deploy.sh_push"
enabled = {"true" if is_mgr else "false"}
'''

open(out, "w").write(body)
os.chmod(out, 0o600)
print(f"[init] wrote {out}")
PY
    fi

    # derive one agent.toml per host from the (authoritative) manager.toml
    MGR_ADDR="$mgr_addr" python3 - "$mgr_toml" "$SECRETS" "$(manager_id)" <<'PY'
import os, re, sys
mgr_toml, secrets_dir, mgr_id = sys.argv[1], sys.argv[2], sys.argv[3]
t = open(mgr_toml).read()
mgr_addr = os.environ["MGR_ADDR"]

blocks = re.split(r'^\[\[hosts\]\]\s*$', t, flags=re.M)[1:]
for b in blocks:
    f = dict(re.findall(r'^([a-z_]+)\s*=\s*"?([^"\n]+)"?\s*$', b, flags=re.M))
    hid = f["id"].strip('"')
    is_mgr = (hid == mgr_id)
    manager_url = "http://127.0.0.1:8080" if is_mgr else f"http://{mgr_addr}:8080"
    body = f'''host_id = "{hid}"
github_url = "https://github.com/your-org"
manager_url = "{manager_url}"
manager_token = "{f['manager_token']}"
listen_token = "{f['agent_token']}"
verify_tls = false
disk_mounts = ["/home", "/"]
toolcache_idle_days = 14
'''
    p = os.path.join(secrets_dir, f"agent-{hid}.toml")
    open(p, "w").write(body); os.chmod(p, 0o600)
    print(f"[init] wrote {p}")
PY

    echo
    echo "[init] next:"
    echo "  1. edit secrets/manager.toml -> [github] app_id + installation_id"
    echo "  2. cp <app private key>.pem secrets/github-app.pem"
    echo "  3. ./deploy.sh push $(manager_id)"
}

# ============================================================ push
cmd_push() {
    local target="${1:?usage: deploy.sh push <host-id|all>}"
    [[ -d "$SECRETS" ]] || die "run ./deploy.sh init first"
    if [[ "$target" == "all" ]]; then
        # manager host first so agents can reach it
        local m; m="$(manager_id)"
        [[ -n "$m" ]] && cmd_push "$m"
        for id in $(all_host_ids); do [[ "$id" == "$m" ]] || cmd_push "$id"; done
        return
    fi

    host_row "$target" >/dev/null || die "unknown host id: $target"
    local ssh_t role lan allow
    ssh_t="$(host_field "$target" 2)"
    role="$(host_field "$target" 3)"
    lan="$(host_field "$target" 4)"
    allow="$(host_field "$target" 5)"
    [[ -f "$SECRETS/agent-$target.toml" ]] || die "secrets/agent-$target.toml missing — re-run init"

    echo
    echo "========================================================"
    echo "  push $target   ($ssh_t, role=$role)"
    echo "========================================================"

    # 0. runner tarball must be staged locally (ghcr.io + GitHub's asset CDN are
    #    throttled from these hosts, so the image can't fetch it during build).
    local rv="${RUNNER_VERSION:-2.337.0}" tb
    tb="containerfile/actions-runner-linux-x64-${rv}.tar.gz"
    if [[ ! -f "$tb" ]]; then
        echo "[deploy 0/4] runner tarball missing — fetching v${rv} from GitHub…"
        if ! curl -fL --connect-timeout 15 --max-time 600 -o "${tb}.part" \
              "https://github.com/actions/runner/releases/download/v${rv}/actions-runner-linux-x64-${rv}.tar.gz"; then
            rm -f "${tb}.part"
            die "could not download the runner tarball from this machine. Stage it manually:
       scp <a-host-with-github-access>:/tmp/actions-runner-linux-x64-${rv}.tar.gz $tb
     (or from any host/machine that can reach release-assets.githubusercontent.com)"
        fi
        mv "${tb}.part" "$tb"
    fi
    echo "[deploy 0/4] runner tarball: $tb ($(du -h "$tb" | cut -f1))"

    # 1. stage code + per-host secrets
    echo "[deploy 1/4] syncing code + config to $ssh_t:$REMOTE_STAGE …"
    ssh "$ssh_t" "rm -rf $REMOTE_STAGE && mkdir -p $REMOTE_STAGE"
    rsync -a --delete \
        --exclude secrets --exclude .git --exclude '*.db*' --exclude __pycache__ --exclude .claude \
        ./ "$ssh_t:$REMOTE_STAGE/"
    rsync -a "$SECRETS/agent-$target.toml" "$ssh_t:$REMOTE_STAGE/_agent.toml"
    if [[ "$role" == "manager" ]]; then
        rsync -a "$SECRETS/manager.toml" "$ssh_t:$REMOTE_STAGE/_manager.toml"
        if [[ -f "$SECRETS/github-app.pem" ]]; then
            rsync -a "$SECRETS/github-app.pem" "$ssh_t:$REMOTE_STAGE/_github-app.pem"
            echo "             + manager.toml + github-app.pem"
        else
            echo "  !! secrets/github-app.pem missing — UI runs but runner registration is off"
        fi
    fi
    echo "[deploy 1/4] done."

    # 2. host bootstrap (root, interactive sudo)
    local setup_args="--role $role"
    [[ "$role" == "manager" && -n "$lan" ]] && setup_args+=" --lan-cidr $lan"
    [[ "$role" == "agent"   && -n "$allow" ]] && setup_args+=" --allow-from $allow"
    echo "[deploy 2/4] host bootstrap (setup-host.sh $setup_args) — sudo password prompt follows"
    ssh -t "$ssh_t" "sudo bash '$REMOTE_STAGE/host/setup-host.sh' $setup_args"
    echo "[deploy 2/4] done."

    # 3. install app + config + units — stage the remote script as a file so we
    #    can run it under `ssh -t sudo bash FILE` (no heredoc-on-stdin vs -t clash)
    echo "[deploy 3/4] installing app + building venvs + runner image (several minutes on first run)"
    echo "             — sudo password prompt follows; live progress is from the host —"
    sed -e "s|@@STAGE@@|$REMOTE_STAGE|g" -e "s|@@USER@@|$RUNNER_USER|g" -e "s|@@TARGET@@|$target|g" \
        host/remote-install.sh | ssh "$ssh_t" "cat > $REMOTE_STAGE/_install.sh"
    ssh -t "$ssh_t" "sudo bash '$REMOTE_STAGE/_install.sh'"
    echo "[deploy 3/4] done."

    # 4. record this agent's fingerprint, refresh the manager
    echo "[deploy 4/4] recording fingerprint + refreshing manager config"
    local fpr; fpr="$(ssh "$ssh_t" "cat '$REMOTE_STAGE/_fingerprint' 2>/dev/null" | tr -d '[:space:]')"
    [[ -n "$fpr" ]] || fpr="$(cmd_fingerprint "$target" | tr -d '[:space:]')"
    [[ "$fpr" == sha256:* ]] || { echo "  ! could not read a valid fingerprint for $target (got '$fpr')"; echo "=== $target incomplete ==="; return; }
    echo "[deploy 4/4] $target agent fingerprint: $fpr"
    python3 - "$SECRETS/manager.toml" "$target" "$fpr" <<'PY'
import re, sys
path, hid, fpr = sys.argv[1:4]
t = open(path).read()
blocks = re.split(r'(?=^\[\[hosts\]\])', t, flags=re.M)
for i, b in enumerate(blocks):
    if re.search(rf'^id = "{re.escape(hid)}"\s*$', b, flags=re.M):
        blocks[i] = re.sub(r'agent_tls_fingerprint = "[^"]*"',
                           f'agent_tls_fingerprint = "{fpr}"', b)
open(path, "w").write("".join(blocks))
print(f"[deploy] recorded fingerprint for {hid}: {fpr[:23]}…")
PY

    local mgr_id mgr_ssh; mgr_id="$(manager_id)"; mgr_ssh="$(host_field "$mgr_id" 2)"
    if [[ "$target" == "$mgr_id" ]]; then
        echo "[deploy 4/4] this IS the manager host — _install.sh already pinned + restarted it"
    elif [[ -n "$mgr_ssh" ]]; then
        echo "[deploy 4/4] pushing updated manager.toml to $mgr_id and restarting the manager"
        rsync -a "$SECRETS/manager.toml" "$mgr_ssh:$REMOTE_STAGE/_manager.toml"
        ssh -t "$mgr_ssh" "sudo bash -c '
            H=\$(getent passwd $RUNNER_USER | cut -d: -f6); U=\$(id -u $RUNNER_USER)
            install -o $RUNNER_USER -g $RUNNER_USER -m 600 $REMOTE_STAGE/_manager.toml \"\$H/.config/sp-runner/manager.toml\"
            runuser -u $RUNNER_USER -- env XDG_RUNTIME_DIR=/run/user/\$U systemctl --user try-restart sp-runner-manager.service 2>/dev/null || true
        '"
    fi
    echo
    echo "=== $target done — UI: http://$(host_field "$mgr_id" 2 | cut -d@ -f2):8080 ==="
}

cmd_fingerprint() {
    local id="${1:?}" ssh_t
    ssh_t="$(host_field "$id" 2)"; [[ -n "$ssh_t" ]] || die "unknown host: $id"
    # prefer the file deploy left; else read the cert via sudo (-t for the prompt)
    local f; f="$(ssh "$ssh_t" "cat '$REMOTE_STAGE/_fingerprint' 2>/dev/null" | tr -d '[:space:]')"
    if [[ "$f" == sha256:* ]]; then printf '%s\n' "$f"; return; fi
    ssh -t "$ssh_t" "sudo cat \$(getent passwd $RUNNER_USER | cut -d: -f6)/.config/sp-runner/agent.crt" 2>/dev/null \
        | openssl x509 -noout -fingerprint -sha256 2>/dev/null \
        | sed 's/^.*=//' | tr -d ':' | tr 'A-F' 'a-f' | sed 's/^/sha256:/'
}

case "${1:-}" in
    init)        cmd_init ;;
    push)        shift; cmd_push "${1:-}" ;;
    fingerprint) shift; cmd_fingerprint "${1:-}" ;;
    *) sed -n '3,8p' "$0" >&2; exit 1 ;;
esac
